apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: myemail@company.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret used to store the account's private key.
      name: cluster-issuer-prod-key
    # Add a ACME HTTP01 challenge solver
    solvers:
    - http01:
        ingress: {}
